baseURL: "https://rohitahuja.dev/"
title: Rohit Ahuja
languageCode: en-us
theme: PaperMod

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 50
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: experience
      name: Experience
      url: /experience
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 60

params:
  # theme
  showToc: true
  tocopen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Rohit Ahuja"
    subtitle: "Portfolio and Blog of Rohit Ahuja"
    imageUrl: "cropped.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: rohit-ahuja-headshot
    #buttons:
    #  - name: Resume
    #    url: https://drive.google.com/file/d/14_ZVPl4dO_r0uctZKqFaqJWwiXq5HsF2/view?usp=sharing

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:rohit23ahuja@gmail.com"  
    - name: "linkedin"
      url: "https://www.linkedin.com/in/rohit-ahuja-6b513783/"
    - name: "github"
      url: "https://github.com/rohit23ahuja"
    - name: "cv"
      url: "https://drive.google.com/file/d/14_ZVPl4dO_r0uctZKqFaqJWwiXq5HsF2/view?usp=sharing"        
    - name: "twitter"
      url: "https://twitter.com/rohit23ahuja"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary    

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
